Repository education/classroom-assistant, pull requests merged in 2018-09, with the labels that each got.

#53 Updates to Authentication for new Classroom API and Private Repo Cloning
  app/main.js
  app/modules/assignment/__tests__/selectors-test.js
  app/modules/assignment/actions/__tests__/assignment-fetch-info-test.js
  app/modules/assignment/actions/__tests__/assignment-receive-info-test.js
  app/modules/assignment/actions/assignment-fetch-info.js
  app/modules/assignment/actions/assignment-receive-info.js
  app/modules/assignment/reducers/__tests__/assignment-test.js
  app/modules/assignment/reducers/assignment.js
  app/modules/assignment/selectors.js
  app/modules/pagination/actions/__tests__/pagination-fetch-all-test.js
  app/modules/pagination/actions/__tests__/pagination-fetch-page-test.js
  app/modules/pagination/actions/pagination-fetch-all.js
  app/modules/pagination/actions/pagination-fetch-page.js
  app/modules/settings/actions/__tests__/settings-fetch-user-from-keychain-test.js
  app/modules/settings/actions/__tests__/settings-login-user-test.js
  app/modules/settings/actions/__tests__/settings-logout-user-test.js
  app/modules/settings/actions/__tests__/settings-reset-state-test.js
  app/modules/settings/actions/__tests__/settings-update-user-state-test.js
  app/modules/settings/actions/settings-fetch-user-from-keychain.js
  app/modules/settings/actions/settings-login-user.js
  app/modules/settings/actions/settings-logout-user.js
  app/modules/settings/actions/settings-reset-state.js
  app/modules/settings/actions/settings-update-user-state.js
  app/modules/submissions/actions/__tests__/submission-clone-test.js
  app/modules/submissions/actions/submission-clone.js
  app/routes/AppContainer.jsx
  app/routes/populate/populate.jsx
  app/userAuthentication.js
  package-lock.json
  package.json
  test/setup.js
Labels: :rocket: Ready for Review, :tada: MVP Release

#59 Fixes for Windows squirell updates + protocol handling
  app/lib/pathutils.js
  app/main.js
  package-lock.json
  package.json
Labels: :rocket: Ready for Review, :tada: MVP Release

#63 Fix Multiple Keychain prompts on Mac
  app/main.js
  app/modules/assignment/actions/__tests__/assignment-fetch-info-test.js
  app/modules/assignment/actions/assignment-fetch-info.js
  app/modules/pagination/actions/pagination-fetch-all.js
  app/modules/settings/actions/__tests__/settings-fetch-user-from-keychain-test.js
  app/modules/settings/actions/__tests__/settings-logout-user-test.js
  app/modules/settings/actions/settings-fetch-user-from-keychain.js
  app/modules/settings/actions/settings-logout-user.js
  app/modules/submissions/actions/__tests__/submission-clone-test.js
  app/modules/submissions/actions/submission-clone.js
  app/userAuthentication.js
Labels: :rocket: Ready for Review, :tada: MVP Release, bug

#61 Fix Windows UI Issues
  app/main.js
  app/menu.js
  app/routes/archive/components/ItemArchivePanel.jsx
  app/routes/archive/components/__tests__/ItemArchivePanel-test.js
  app/routes/index/index.jsx
  app/routes/populate/populate.jsx
  app/routes/shared/components/Header.jsx
  app/styles/routes/shared/_header.scss
  app/userAuthentication.js
Labels: :rocket: Ready for Review, :tada: MVP Release

#58 Bump electron version to 1.8.8
  package-lock.json
  package.json
Labels: :tada: MVP Release

#73 Rename Classroom Desktop -> Classroom Assistant
  README.md
  app/routes/index/index.jsx
  app/styles/routes/_index.scss
Labels: :rocket: Ready for Review, :tada: MVP Release
